[TEVA-1520] Add jobseeker account feedback feature
DFE-Digital/teaching-vacancies pull request #2525
Opened 2020-12-14 22:08 UTC by cesidio

## Jira ticket URL
https://dfedigital.atlassian.net/browse/TEVA-1520

## Screenshots of UI changes:
![Screenshot 2020-12-14 at 22 06 18](https://user-images.githubusercontent.com/7215/102141492-ce0dff00-3e58-11eb-8205-f4f22c8dacb5.png)
![Screenshot 2020-12-14 at 22 06 50](https://user-images.githubusercontent.com/7215/102141502-d108ef80-3e58-11eb-8168-dc4c6c244f29.png)
![Screenshot 2020-12-14 at 22 07 03](https://user-images.githubusercontent.com/7215/102141504-d1a18600-3e58-11eb-85d0-1beb08dd205f.png)
![Screenshot 2020-12-14 at 22 07 20](https://user-images.githubusercontent.com/7215/102141505-d1a18600-3e58-11eb-8b8a-1701c47dc970.png)

2020-12-14 22:21 UTC, martin-bangoura commented
Review app deployed to <https://teaching-vacancies-review-pr-2525.london.cloudapps.digital>
<!-- Sticky Pull Request Comment -->

2020-12-15 08:39 UTC, cpjmcquillan approved these changes
Just a minor couple of comments

2020-12-15 08:39 UTC, cpjmcquillan commented on app/components/jobseekers/account_survey_link_component/account_survey_link_component.scss
> +    color: govuk-colour('black');
Single or double quotes? (See above and below)

2020-12-15 08:39 UTC, cpjmcquillan commented on app/views/jobseekers/account_feedbacks/new.html.haml
> +      = f.govuk_radio_buttons_fieldset(:rating) do
Can we not use the radio collection?

2020-12-15 16:20 UTC, david-mears-dfe requested changes
Please ask Content Design for a better error message than the default inclusion error.

> ![Screenshot 2020-12-14 at 22 07 03](https://user-images.githubusercontent.com/7215/102141504-d1a18600-3e58-11eb-85d0-1beb08dd205f.png)

2020-12-15 17:46 UTC, cesidio commented
> Please ask Content Design for a better error message than the default inclusion error.
> 
> > ![Screenshot 2020-12-14 at 22 07 03](https://user-images.githubusercontent.com/7215/102141504-d1a18600-3e58-11eb-85d0-1beb08dd205f.png)

Yes I sent already 2 messages to ask for that. I am waiting for that content. I am not going to merge it like this

2020-12-16 15:41 UTC, david-mears-dfe approved these changes

2020-12-16 15:42 UTC, merged