Display the right number of vacancies awaiting feedback.
DFE-Digital/teaching-vacancies pull request #3102
Opened 2021-03-17 20:13 UTC by david-mears-dfe

For school groups, 'organisation.vacancies' will only retrieve vacancies with a location of 'central_office', rather than all vacancies at the organisation.

2021-03-24 11:19 UTC, david-mears-dfe commented
I'm going to redo the test as a request spec.

2021-03-24 13:04 UTC, martin-bangoura commented
Review app deployed to <https://teaching-vacancies-review-pr-3102.london.cloudapps.digital>
<!-- Sticky Pull Request Comment -->

2021-03-24 13:10 UTC, david-mears-dfe commented on app/controllers/publishers/omniauth_callbacks_controller.rb
> +    # https://github.com/DFE-Digital/login.dfe.public-api#how-do-ids-map-to-categories-and-types
(My forked change was accepted into their README)

2021-03-25 15:46 UTC, cesidio requested changes
we should not create anymore controller specs and have request specs instead

2021-03-26 10:20 UTC, david-mears-dfe commented
> we should not create anymore controller specs and have request specs instead

I don't think request specs can check variable assignment, as I said in the description. So I will create a method on vacancies_awaiting_feedback_count method on Organisation, and test that.

2021-03-26 14:44 UTC, cesidio commented
Having had a better think about the problem here, and having discussed about it with Christian, I think that the best solution  is not to test this specific thing as we have system specs that cover the happy path. I would just have the minimum change that fix the problem.

2021-03-26 15:18 UTC, cesidio approved these changes

2021-03-26 22:04 UTC, merged