[TEVA-3417] Convert map to stimulus.js and OpenStreetMap
DFE-Digital/teaching-vacancies pull request #4383
Opened 2021-12-06 11:11 UTC by cesidio

## Jira ticket URL

https://dfedigital.atlassian.net/browse/TEVA-3417

## Screenshots of UI changes:

### Before
![Screenshot 2021-12-06 at 11 09 41](https://user-images.githubusercontent.com/7215/144836247-555c1326-8dc7-44f3-85e8-305639f855f9.png)

### After
![Screenshot 2021-12-06 at 11 10 25](https://user-images.githubusercontent.com/7215/144836192-72017536-d44d-4465-9d5d-ba497bf4c157.png)

2021-12-06 14:25 UTC, csutter requested changes
Looks good - see comment about the licence attribution.

I reckon we can go live with OSM, and then maybe switch to Mapbox if we think that's useful.

2021-12-06 14:25 UTC, csutter commented on app/components/map_component/map.js
> +    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(this.map);
We need to add OSM attribution to the map to comply with their licence:

```js
L.tileLayer(
  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }
).addTo(this.map);
```

2021-12-06 21:35 UTC, david-mears-dfe commented
This version of Essex (which has multiple polygons because it has islands) worries me. Is this a flaw in the debugging tool or in the location search itself? If the debugging tool is making me think there is a bug when there isn't, we could consider getting rid of the debugging tool rather than trying to invest time in debugging it. Or I can put it on the Christmas firebreak list...

<img width="1126" alt="Screenshot 2021-12-06 at 21 33 36" src="https://user-images.githubusercontent.com/60350599/144926121-eefadb17-2758-49f4-b393-7db4aeafd51b.png">

2021-12-07 09:25 UTC, csutter approved these changes

2021-12-07 11:02 UTC, alexbowen commented
tested and working on IE11

2021-12-07 11:05 UTC, alexbowen approved these changes

2021-12-07 11:16 UTC, cesidio commented
> This version of Essex (which has multiple polygons because it has islands) worries me. Is this a flaw in the debugging tool or in the location search itself? If the debugging tool is making me think there is a bug when there isn't, we could consider getting rid of the debugging tool rather than trying to invest time in debugging it. Or I can put it on the Christmas firebreak list...
> 
> <img alt="Screenshot 2021-12-06 at 21 33 36" width="1126" src="https://user-images.githubusercontent.com/60350599/144926121-eefadb17-2758-49f4-b393-7db4aeafd51b.png">

This has now been fixed, can you please test it again as soon as the new review app will build? Thanks for reporting it David! :)

2021-12-08 10:18 UTC, merged