Update Ruby to 3.1
DFE-Digital/teaching-vacancies pull request #4488
Opened 2022-01-10 15:50 UTC by csutter

- (Temporarily) add `net-*` gems to Gemfile (which have been split out
  from stdlib into separate gems in Ruby 3.1, but aren't explicit
  dependencies of Rails yet)

2022-01-11 14:53 UTC, elliotcm requested changes
I'm going to pause this review at 100 files in, should we make it so that we never end a line with `:`?  Typically in views where we'd e.g. end with `f: f` it now just ends `f:` and looks like a Python block.

2022-01-11 14:53 UTC, elliotcm commented on app/views/jobseekers/job_applications/index.html.slim
> +            = render "job_application", job_application:
```suggestion
            = render("job_application", job_application:)
```

2022-01-11 14:53 UTC, elliotcm commented on app/views/jobseekers/job_applications/index.html.slim
> +            = render "job_application", job_application:
```suggestion
            = render("job_application", job_application:)
```

2022-01-11 14:53 UTC, elliotcm commented on app/views/jobseekers/job_applications/index.html.slim
> +            = render "job_application", job_application:
```suggestion
            = render("job_application", job_application:)
```
These can potentially all be replaced by `= render(job_application)`.

2022-01-11 14:53 UTC, elliotcm commented on app/views/jobseekers/registrations/edit.html.slim
> +          = render "edit_email", f:
```suggestion
          = render("edit_email", f:)
```

2022-01-12 09:20 UTC, csutter commented
Given the outstanding questions about hash literals in certain contexts (@elliotcm raises some excellent points), and the fact that Brakeman doesn't support 3.1 syntax yet anyway, I'll close this PR and open a new one without the changes and with the Rubocop rule disabled.

Let's revisit this in the future though.

2022-01-12 09:20 UTC, closed without merging