Add candidates profile page for hiring staff
DFE-Digital/teaching-vacancies pull request #5846
Opened 2023-03-06 09:55 UTC by ddippolito

## Trello ticket URL

https://trello.com/c/HqhW42iW/129-candidate-profiles-page-for-hiring-staff-users

## Changes in this PR:

This PR adds a  Jobseeker Profile page in the Hiring Staff journey. The default scope for the page displays profiles in the school area and applies filters.

## Screenshots of UI changes:

<img width="1214" alt="Screenshot 2023-03-06 at 09 53 41" src="https://user-images.githubusercontent.com/1470166/223076744-e993fdd2-42fa-482d-9eff-36deaf46fe18.png">

## Next steps:

Testing and adding Mats school filtering

2023-03-06 10:12 UTC, elliotcm requested changes
A few small tweaks requested, but otherwise looking good.

2023-03-06 10:12 UTC, elliotcm commented on app/assets/stylesheets/application.scss
> +@import 'layouts/posts/index';
Duplicate of the line above?

2023-03-06 10:12 UTC, elliotcm commented on app/views/publishers/jobseeker_profiles/search/_results.html.slim
> +        = govuk_link_to jobseeker_profile.full_name, "/"
```suggestion
        = govuk_link_to jobseeker_profile.full_name, root_path
```

2023-03-06 10:12 UTC, elliotcm commented on app/views/publishers/jobseeker_profiles/search/_results.html.slim
> +        - if jobseeker_profile.job_preferences.present?
We just need one of these `if` statements for all three summary list rows.

2023-03-06 10:12 UTC, elliotcm commented on config/locales/publishers.yml
> +      preferred_key_stage: "Preferred key stage:s"
Typo?

2023-03-06 10:31 UTC, elliotcm commented on app/views/publishers/jobseeker_profiles/search/_results.html.slim
> +        = govuk_link_to jobseeker_profile.full_name, "/"
Right yes, ignore this then.

2023-03-06 10:37 UTC, elliotcm approved these changes

2023-03-08 10:07 UTC, bencmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Candidate profiles" page for Hiring staff users](https://trello.com/c/HqhW42iW/129-candidate-profiles-page-for-hiring-staff-users)

2023-03-09 15:25 UTC, merged