[179] Notification banner shown on jobseeker account on sign in after feature release
DFE-Digital/teaching-vacancies pull request #5875
Opened 2023-03-15 13:28 UTC by georges1996

https://trello.com/c/7aCsfF4e/179-notification-banner-shown-on-jobseeker-account-on-first-sign-in-after-feature-release

## Changes in this PR:

- Show the profiles banner when their profile is incomplete

## Screenshots of UI changes

2023-03-15 14:40 UTC, bencmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notification banner shown on jobseeker account on first sign in after feature release](https://trello.com/c/7aCsfF4e/179-notification-banner-shown-on-jobseeker-account-on-first-sign-in-after-feature-release)

2023-03-15 15:46 UTC, elliotcm requested changes

2023-03-15 15:46 UTC, elliotcm commented on app/controllers/jobseekers/saved_jobs_controller.rb
> +
```suggestion
```

2023-03-15 15:46 UTC, elliotcm commented on app/controllers/jobseekers/saved_jobs_controller.rb
> +  end
```suggestion
  def show_candidate_profiles_banner?
    profile = current_jobseeker.jobseeker_profile
    personal_details = profile.personal_details
    job_preferences = profile.job_preferences

    section_completed(personal_details) && section_completed(job_preferences)
  end
  helper_method :show_candidate_profiles_banner?
```

2023-03-15 15:46 UTC, elliotcm commented on app/controllers/jobseekers/saved_jobs_controller.rb
> +  end
```suggestion
  def section_completed(record)
    return if record.completed_steps.blank?

    step_phases = %w[completed skipped]
    record.completed_steps.values.all? { |step| step_phases.include?(step) }
  end
```

2023-03-15 15:46 UTC, elliotcm commented on app/views/jobseekers/saved_jobs/index.html.slim
> +      = render "candidiate_profiles_banner"
This seems to be inverted?

```suggestion
    = render "candidiate_profiles_banner" if show_candidate_profiles_banner?
```

2023-03-16 08:41 UTC, bencmitchell commented
@georgeschena looks good to me 👍

2023-03-16 08:54 UTC, elliotcm approved these changes

2023-03-23 16:54 UTC, merged