Add API clients management section to supportal
DFE-Digital/teaching-vacancies pull request #7242
Opened 2024-11-08 10:27 UTC by ddippolito

## Trello card URL
https://trello.com/c/BGZc9dco/1327-add-api-clients-management-to-supportal

## Changes in this PR:
This adds a new section to the support for managing API clients. 
We will shortly build a new vacancies API and migrate the existing ATS integrations towards it.

## Screenshots of UI changes:
<img width="471" alt="Screenshot 2024-11-08 at 10 20 06" src="https://github.com/user-attachments/assets/0978289b-78f4-4032-9ecd-91c0ef15678c">
<img width="1043" alt="Screenshot 2024-11-08 at 10 43 53" src="https://github.com/user-attachments/assets/9c0cb903-cd8b-45cc-a96f-a77e5e42783e">
<img width="1029" alt="Screenshot 2024-11-08 at 10 20 42" src="https://github.com/user-attachments/assets/e8d1a551-b12b-4dae-92a0-b77c81443419">
<img width="1009" alt="Screenshot 2024-11-08 at 10 45 20" src="https://github.com/user-attachments/assets/4d6bb43e-b866-4479-9fce-1dc999008d7a">

2024-11-11 09:28 UTC, starswan commented on app/models/api_client.rb
> +    self.api_key ||= SecureRandom.hex(20)
should this not set last_rotated_at? Then it can be non-null

2024-11-12 10:46 UTC, starswan approved these changes

2024-11-12 11:40 UTC, scruti requested changes
The PR approach is great. Just what we needed and will make the ATS API management so much better.

My only request is to make the wording more specific.

Since this is a very specific API and subset of users and we have another API around, talking about "API" and "API Clients" seems quite generic and prone to confusion.

I would change it for `Publishers ATS API` or `Publishers API`. So it is clear what we are talking about.

`API Clients` 

![image](https://github.com/user-attachments/assets/428409a6-5dfe-4df1-bb6b-a5349c95e356)

2024-11-12 15:26 UTC, scruti commented on app/controllers/support_users/api_clients_controller.rb
> +class SupportUsers::ApiClientsController < ApplicationController
This is publicly accessible and doesn't require authentication. 

![image](https://github.com/user-attachments/assets/51062879-0e0c-4e6a-be0f-43c50aede000)

2024-11-14 09:39 UTC, merged